name: Node.js CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    defaults:
         run:
          working-directory: 'WebClient'
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './WebClient/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
